import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Text, Image } from "@geist-ui/react";
import { useEffect } from "react";
import Photoshot from '../public/projektopgave.png'
import { useRouter } from "next/router";
export default function Home() {
  const router = useRouter();
  useEffect(() => {
    if(!sessionStorage.getItem('mapData')){
      sessionStorage.setItem("mapData", "INVALID");
    }
    
  }, []);

  const handleUpload = (event) => {
    const reader = new FileReader();
    reader.addEventListener('load',() => readFile(reader.result), false);
    if (event.files[0]) {
      reader.readAsText(event.files[0]);
    }
  };

  const readFile = async (result) => {
   
    await sessionStorage.setItem('mapData', result);
    router.push('/submitted')
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Projekt</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Image.Browser url="https://projekt.oscarspalk.com">
        <Image  width="540px" height="246px" src={Photoshot} alt="Screenshot" />
      </Image.Browser>
      <Text mt={2} h3>Upload din lokationsfil nedenfor</Text>
      <input onChange={(e) => handleUpload(e.target)} type="file" />
    </div>
  );
}
